# 开发环境配置(即数据源配置)
# 注: MySQL8.0版本对时区有要求
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_seed?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver